universe   = vanilla
executable = 20GeV.sh
arguments  = $(ProcId)
output     = log/$(ProcId).out
error      = log/$(ProcId).err
log        = log/$(ProcId).log

request_memory = 3 GB

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /u/user/haeun/Sherco/v240501/ShercoSim/install/bin, \
					   /u/user/haeun/Sherco/v240501/ShercoSim/install/lib, \
					   /u/user/haeun/Sherco/v240501/ShercoSim/install/init.mac, \
					   /u/user/haeun/Sherco/v240501/ShercoSim/install/20GeV.mac, \
					   /u/user/haeun/Sherco/v240501/ShercoSim/install/AbsLength_LS.txt

JobBatchName = mu_20GeV

queue 100
